language: python
os:
  - linux

python:
  - "2.7"
before_script:
 - chmod +x binaries
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest